esphome:
  name: h801_scrivania
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

  ap:
    ssid: 'Barra scrivania'
    password: !secret wifi_pass

captive_portal:

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_w2

light:
  - platform: rgbww
    name: "Barra scrivania"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    warm_white: pwm_w1
    cold_white: pwm_w2
    warm_white_color_temperature: 2700 K
    cold_white_color_temperature: 6000 K
    color_interlock: true
    restore_mode: RESTORE_DEFAULT_OFF

switch:
  - platform: restart
    name: "LED Scrivania Reboot"
